apiVersion: v1
kind: Service
metadata:
  namespace: testing
  name: db-service
  labels:
    name: ets-sweng-asal-db-service
spec:
  selector:
    app: ets-sweng-asal-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
