kind: Service
apiVersion: v1
metadata:
  namespace: testing
  name: jvm-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: ets-sweng-asal
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8443
  type: LoadBalancer
