apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: testing 
  name: static-db-deployment-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: azurefilestorage
