apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: testing
  name: static-db-persistence-volume
  labels: 
    storage: slow
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  storageClassName: azurefilestorage
  azureFile:
    secretName: static-persistence-secret
    shareName: storage
    readOnly: false
  
