apiVersion: v1
kind: Secret
metadata:
  namespace: testing
  name: static-persistence-secret
type: Opaque
data:
  azurestorageaccountname: cmFuY2hlcmRldg== 
  azurestorageaccountkey: WUoxNFg2S3U2cjNzaHhHdFJGeFlkN2xLRVFPOHZyMTZiUjNLdWFtSXZZNkQxQzY4NFJwQjE0K3c5R3hrTWF5TG9OYWlWY1VCYkovdnI0emZzM1BaN3c9PQ==
